### ISSUE TITLE
Discarding partial duplicates & differently ordered duplicates

### ISSUE THREAD

**Issue by ismay** [ben-eb/postcss-discard-duplicates#1]
I was wondering, is there a reason that these kinds of duplicate rules:

``` css
/* Different order */
/*original*/
html {
  font-size: 12px;
  color: black;
}

/*duplicate*/
html {
  color: black;
  font-size: 12px;
}

/*Partial duplication*/
/*original*/
html {
  font-size: 12px;
  color: black;
}

/*duplicate*/
html {
  color: black;
}
```

Are not discarded? Because from what I can tell currently only identical, duplicate blocks are discarded. Which somewhat limits the functionality, as that almost never happens. Shouldn't the duplicates from the examples above be discarded as well? Or could that introduce unwanted behaviour in the resulting css?

**Comment by ben-eb** [comment]
No particular reason, just hadn't considered it. I believe that in the case where the selectors are identical, you can discard the first property because the second will override it. For example:

```css
/* This selector should be discarded */
p {
  color: black;
  font-size: 12px;
}

/* This selector should be kept */
p {
  font-size: 12px;
  color: black;
}
```

I think you are right that this transformation should be this module's responsibility. I'm open to a PR for it, still fairly busy this week, but if not I'll have a look when I can.

**Comment by ismay** [comment]
> I believe that in the case where the selectors are identical, you can discard the first property because the second will override it.

Exactly, and partial duplication can be deleted as well, as that'll be overwritten too. I'd be open for making a PR, but pretty busy right now as well. If I have the time I'll definitely take a look!

**Comment by KingScooty** [comment]
@ben-eb should the first selector be kept, and the latter removed? 

I'm using webpack and the extract text plugin to generate one css file from multiple sass files. I'm noticing that this remove duplicates plugin is removing all the duplicate css resets but the last one, which is half way down the merged css file, which means half the code is being reset after it's been set, which seems like madness?

Surely all subsequent duplicates should be removed, leaving the first in tact?

**Comment by ben-eb** [comment]
@KingScooty I believe that the way that it is calculated right now most closely mirrors what a browser would do in this situation; with the same specificity of a rule, the last one will be applied. In this somewhat contrived example:

```css
h1 {
  color: red;
}

h1 {
  color: green;
}

h1 {
  color: red;
}
```

Keeping the *last* of the duplicated rules (the current behaviour) results in a `red` heading; keeping the *first* results in a `green` heading.

* * *

Is it possible to structure your Sass files so that you have a main `@import` file for your resets? This might be a better solution than removing duplicates post-compilation.
