### ISSUE TITLE
Duplicates with Lost Grid

### ISSUE THREAD

**Issue by custa1200** [ben-eb/postcss-discard-duplicates#25]
Hi, I have the following markup when using Lost Grid

``` css

.form__col__create-account {

  &__firstname {
    lost-column: 1/2;
  }

  &__lastname {
    lost-column: 1/2;
  }

  &__mobile-number {
    lost-column: 1/2;
  }

  &__phone-pin {
    lost-column: 1/2;
  }

  &__alternate-phone-number {
    lost-column 1/2;
  }

  &__address {
    lost-column: 1/2;
  }

  &__atomic-address {
    display: none;
  }

  &__postcode {
    lost-column: 1/2;
  }

  &__state {
    lost-column: 1/2;
  }

  &__rego-state {
    lost-column: 1/2;
  }

  &__rego {
    lost-column: 1/2;
  }

  &__vehicle-make {
    lost-column: 1/3;
  }

  &__vehicle-model {
    lost-column: 1/3;
  }

  &__vehicle-class {
    lost-column: 1/3;
  }

}

```

Which when output and using discard duplicates in my build script I get the following with has a lot of duplicates of a pattern. I wonder if discard duplicates could be made "smarter" to handle such patterns?

``` css
.form__col__create-account__firstname {
  width: calc(99.9% * 1/2 - (30px - 30px * 1/2));
}
.form__col__create-account__firstname:nth-child(1n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
.form__col__create-account__firstname:last-child {
  margin-right: 0;
}
.form__col__create-account__firstname:nth-child(2n) {
  margin-right: 0;
  float: right;
}
.form__col__create-account__firstname:nth-child(2n + 1) {
  clear: both;
}
.form__col__create-account__lastname {
  width: calc(99.9% * 1/2 - (30px - 30px * 1/2));
}
.form__col__create-account__lastname:nth-child(1n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
.form__col__create-account__lastname:last-child {
  margin-right: 0;
}
.form__col__create-account__lastname:nth-child(2n) {
  margin-right: 0;
  float: right;
}
.form__col__create-account__lastname:nth-child(2n + 1) {
  clear: both;
}
.form__col__create-account__mobile-number {
  width: calc(99.9% * 1/2 - (30px - 30px * 1/2));
}
.form__col__create-account__mobile-number:nth-child(1n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
.form__col__create-account__mobile-number:last-child {
  margin-right: 0;
}
.form__col__create-account__mobile-number:nth-child(2n) {
  margin-right: 0;
  float: right;
}
.form__col__create-account__mobile-number:nth-child(2n + 1) {
  clear: both;
}
.form__col__create-account__phone-pin {
  width: calc(99.9% * 1/2 - (30px - 30px * 1/2));
}
.form__col__create-account__phone-pin:nth-child(1n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
.form__col__create-account__phone-pin:last-child {
  margin-right: 0;
}
.form__col__create-account__phone-pin:nth-child(2n) {
  margin-right: 0;
  float: right;
}
.form__col__create-account__phone-pin:nth-child(2n + 1) {
  clear: both;
}
.form__col__create-account__alternate-phone-number {
  width: calc(99.9% * 1/2 - (30px - 30px * 1/2));
}
.form__col__create-account__alternate-phone-number:nth-child(1n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
.form__col__create-account__alternate-phone-number:last-child {
  margin-right: 0;
}
.form__col__create-account__alternate-phone-number:nth-child(2n) {
  margin-right: 0;
  float: right;
}
.form__col__create-account__alternate-phone-number:nth-child(2n + 1) {
  clear: both;
}
.form__col__create-account__address {
  width: calc(99.9% * 1/2 - (30px - 30px * 1/2));
}
.form__col__create-account__address:nth-child(1n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
.form__col__create-account__address:last-child {
  margin-right: 0;
}
.form__col__create-account__address:nth-child(2n) {
  margin-right: 0;
  float: right;
}
.form__col__create-account__address:nth-child(2n + 1) {
  clear: both;
}
.form__col__create-account__atomic-address {
  display: none;
}
.form__col__create-account__postcode {
  width: calc(99.9% * 1/2 - (30px - 30px * 1/2));
}
.form__col__create-account__postcode:nth-child(1n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
.form__col__create-account__postcode:last-child {
  margin-right: 0;
}
.form__col__create-account__postcode:nth-child(2n) {
  margin-right: 0;
  float: right;
}
.form__col__create-account__postcode:nth-child(2n + 1) {
  clear: both;
}
.form__col__create-account__state {
  width: calc(99.9% * 1/2 - (30px - 30px * 1/2));
}
.form__col__create-account__state:nth-child(1n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
.form__col__create-account__state:last-child {
  margin-right: 0;
}
.form__col__create-account__state:nth-child(2n) {
  margin-right: 0;
  float: right;
}
.form__col__create-account__state:nth-child(2n + 1) {
  clear: both;
}
.form__col__create-account__rego-state {
  width: calc(99.9% * 1/2 - (30px - 30px * 1/2));
}
.form__col__create-account__rego-state:nth-child(1n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
.form__col__create-account__rego-state:last-child {
  margin-right: 0;
}
.form__col__create-account__rego-state:nth-child(2n) {
  margin-right: 0;
  float: right;
}
.form__col__create-account__rego-state:nth-child(2n + 1) {
  clear: both;
}
.form__col__create-account__rego {
  width: calc(99.9% * 1/2 - (30px - 30px * 1/2));
}
.form__col__create-account__rego:nth-child(1n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
.form__col__create-account__rego:last-child {
  margin-right: 0;
}
.form__col__create-account__rego:nth-child(2n) {
  margin-right: 0;
  float: right;
}
.form__col__create-account__rego:nth-child(2n + 1) {
  clear: both;
}
.form__col__create-account__vehicle-make {
  width: calc(99.9% * 1/3 - (30px - 30px * 1/3));
}
.form__col__create-account__vehicle-make:nth-child(1n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
.form__col__create-account__vehicle-make:last-child {
  margin-right: 0;
}
.form__col__create-account__vehicle-make:nth-child(3n) {
  margin-right: 0;
  float: right;
}
.form__col__create-account__vehicle-make:nth-child(3n + 1) {
  clear: both;
}
.form__col__create-account__vehicle-model {
  width: calc(99.9% * 1/3 - (30px - 30px * 1/3));
}
.form__col__create-account__vehicle-model:nth-child(1n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
.form__col__create-account__vehicle-model:last-child {
  margin-right: 0;
}
.form__col__create-account__vehicle-model:nth-child(3n) {
  margin-right: 0;
  float: right;
}
.form__col__create-account__vehicle-model:nth-child(3n + 1) {
  clear: both;
}
.form__col__create-account__vehicle-class {
  width: calc(99.9% * 1/3 - (30px - 30px * 1/3));
}
.form__col__create-account__vehicle-class:nth-child(1n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
.form__col__create-account__vehicle-class:last-child {
  margin-right: 0;
}
.form__col__create-account__vehicle-class:nth-child(3n) {
  margin-right: 0;
  float: right;
}
.form__col__create-account__vehicle-class:nth-child(3n + 1) {
  clear: both;
}
```

**Comment by ben-eb** [comment]
I'm not sure how we can configure this for an optimal output. As far as I'm concerned, you could do much better by consolidating these rules manually;

```css
.form__col__create-account {
  &__firstname,
  &__lastname
  /*, etc */ {
    lost-column: 1/2;
  }
}
```

However, you have so many of these that it might be wise to define a utility class and use that instead.

```css
.form__col__create-account {
  &__one-half {
    lost-column: 1/2;
  }

  &__one-third {
    lost-column: 1/3;
  }
}
```
