### ISSUE TITLE
bad check color [bag]

### ISSUE THREAD

**Issue by retyui** [ben-eb/postcss-discard-duplicates#38]
Pls normalize color values)
**Input:**
```css
.test{
    color: #FFF;}

.test{
    color: #fff;}
```
**Output:**
```css
.test{
    color: #FFF;}

.test{
    color: #fff;}
```
