### ISSUE TITLE
Order in css matters

### ISSUE THREAD

**Issue by yporodko** [ben-eb/postcss-discard-duplicates#42]
I found weird behavior when this plugin put common rules near the end of css bundle, using css import for react components.

Here is example input made by webpack and plugins (pseudo code):
```css
// import for primary button component
.default-button {
  border: none;
  background-color: grey;
}

.primary-button {
  border: 1px solid blue;
  background-color: light-blue;
}

// import for secondary button component
.default-button {
  border: none;
  background-color: grey;
}

.secondary-button {
  border: 1px solid green;
  background-color: light-green;
}
```

after css passing `postcss-discard-duplicates` we have:
```css
// import for primary button component

.primary-button {
  border: 1px solid blue;
  background-color: light-blue;
}

// import for secondary button component
.default-button {
  border: none;
  background-color: grey;
}

.secondary-button {
  border: 1px solid green;
  background-color: light-green;
}
```
because of `.default-button` was duplicated, plugin removed it, but instead of leaving intact first occurance, it left last one. THIS IS THE PROBLEM in CSS world.

because now, element with `class="primary-button default-button"` will have no border and grey background color.

EXPECTED RESULT:
```css
// import for primary button component
.default-button {
  border: none;
  background-color: grey;
}

.primary-button {
  border: 1px solid blue;
  background-color: light-blue;
}

// import for secondary button component

.secondary-button {
  border: 1px solid green;
  background-color: light-green;
}
```
this plugin should leave first occurance of duplicated "nodes".

as a solution, that I tested, in all loops, go from top to bottom. Now all loops are going from bottom to top.
